launcher:
    windowTitle: 'Minecraft BrauTec Launcher'                                                         # Titre de la fenetre du launcher
    browserHomeURL: 'https://update.brautec.de/'                                             # URL de la page affichee en accueil du launcher
    loginURLHTTP: 'http://login.minecraft.net/'                                              # URL de login HTTP
    loginURLHTTPS: 'https://login.minecraft.net/'
    image: 'http://update.brautec.de/images/brautec.png'                              # URL de login HTTPS
    httpsMode: true                                                                           # Utiliser HTTPS?
    loginParameters: 'user={USERNAME}&password={PASSWORD}&version=13'                         # Ne pas toucher, ce sont les parametres mis dans la requete de login
    offlineMode: false                                                                        # Mode Hors-Ligne
    langs:                                                                                    # Fichiers de langues, en ajouter si vous avez les fichiers
        - 'de_DE'
        - 'en_US'
    debugMode: false                                                                           # Mode debug. Ne sert a rien.
    autoConnectServer:
        connect: false                                                                        # Se connecter automatiquement a un serveur ou non.
        address: 's.krim.me'                                                                           # Adresse du serveur a laquelle le launcher doit se connecter
        port: '25500'                                                                              # Port du serveur sur lequel le launcher doit se connecter
updater:
    askUpdateIfAvailable: false                                                                # Demander quand une MaJ est disponible
    updateIfNewVersionAvailable: true                                                         # Mettre a jour lorsque une MaJ est disponible
    customGameDir: true                                                                      # Utiliser un dossier perso
    gameDir: 'tec'                                                                               # Chemin vers le dossier perso
    folderName: 'bdh'                                                                   # Nom du dossier contenant Minecraft
    keyFileName: 'minecraft.key'                                                              # Nom du fichier contenant la cle pour la connexion en HTTPS
    loginFileEncryptionKey: 'passwordfile'                                                    # Nom du fichier contenant les informations de derniere connexion (Lorsque 'Se souvenir de moi' est coche)
    jarList:                                                                                  # Liste des fichiers .jar a charger
        - 'http://update.brautec.de/bins/lwjgl.jar'
        - 'http://update.brautec.de/bins/jinput.jar'
        - 'http://update.brautec.de/bins/lwjgl_util.jar'
        - 'http://update.brautec.de/bins/minecraft.jar'
    additionalsFiles:                                                                         # Liste des fichiers .zip/.jar additionnels a decompiler dans le dossier de Minecraft
        - 'http://update.brautec.de/mods_base.zip'
        - 'http://update.brautec.de/mods.zip'
        - 'http://update.brautec.de/config.zip'
    configFile:
        - 'http://update.brautec.de/profiles.zip'
    nativesList:                                                                              # Liste des fichiers necessaires pour LWJGL (OpenGL), ne pas toucher sauf si vous les hebergez vous meme
        windows: 'http://update.brautec.de/bins/natives/windows_natives.jar.lzma'
        linux: 'http://update.brautec.de/bins/natives/linux_natives.jar.lzma'
        macos: 'http://update.brautec.de/bins/natives/macosx_natives.jar.lzma'
        macosx: 'http://update.brautec.de/bins/natives/macosx_natives.jar.lzma'
        solaris: 'http://update.brautec.de/bins/natives/solaris_natives.jar.lzma'
    customVersion:
        use: true                                                                            # Utiliser un fichier de version supplementaire (true,yes pour oui. false, no pour Non
        fileName: 'cversion'                                                                  # Nom du fichier de version supplementaire
        checkUrl: 'http://update.brautec.de/version'                          # URL vers le fichier de version heberge
        updateIfAvailable: true                                                               # Mettre a jour si une MaJ est disponible
gameLauncher:
    gameName: 'BrauTec'                                                                     # Titre de la fenetre du jeu
    documentBaseURL: 'http://www.minecraft.net/game/'                                         # Je sais pas trop a quoi ca sert x) Mais je prefere le mettre ici, au cas ou ca vous amuse de le modifier :D
    gameHost: 'www.minecraft.net'                                                             # Idem.